const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Behaviors.MoveTo,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Plugins.Audio,
		C3.Plugins.Button,
		C3.Behaviors.Persist,
		C3.Plugins.TextBox,
		C3.Plugins.sliderbar,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Text.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetPosToObject,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Button.Acts.SetY,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.sliderbar.Acts.SetY,
		C3.Plugins.sliderbar.Acts.SetValue,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.TextBox.Acts.SetPosToObject,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Button.Cnds.IsChecked,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.TextBox.Acts.SetFocus,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Sprite.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{GotoX: 0},
	{GotoY: 0},
	{Button: 0},
	{Layout: 0},
	{GoingBack: 0},
	{MoveTo: 0},
	{MovingText: 0},
	{Mouse: 0},
	{Touch: 0},
	{Number: 0},
	{IsNumber: 0},
	{Backspace: 0},
	{IsSubmitKeypad: 0},
	{IsCheck: 0},
	{IsSubmitKeyboard: 0},
	{isX: 0},
	{ButtonFunction: 0},
	{Buttons: 0},
	{ChangeCurser: 0},
	{TimerDisplay: 0},
	{InputText: 0},
	{TimerDidgets1: 0},
	{TimerDidgets2: 0},
	{TimerDidgets3: 0},
	{Colon: 0},
	{TimerDidgets4: 0},
	{Number1: 0},
	{NumberAlignment: 0},
	{Number2: 0},
	{Number3: 0},
	{Number4: 0},
	{Number5: 0},
	{Number6: 0},
	{Number7: 0},
	{Number8: 0},
	{Number9: 0},
	{Number10: 0},
	{Audio: 0},
	{Batch: 0},
	{Timer: 0},
	{Persist: 0},
	{OptionSelect: 0},
	{OptionText1: 0},
	{GotoMenu: 0},
	{FakeCountdownToggle: 0},
	{KeyboardInput: 0},
	{ActiveKeyboard: 0},
	{ActivKeyboardLabel: 0},
	{GotoMenu2: 0},
	{OptionText2: 0},
	{VolumeBar: 0},
	{FakeVolumeBar: 0},
	{Browser: 0},
	{Fullscreen: 0},
	{Exit: 0},
	{Batch3Wait: 0},
	{Didget1: 0},
	{Didget2: 0},
	{Didget3: 0},
	{Didget4: 0},
	{Seconds: 0},
	{Volume: 0},
	{Minutes: 0},
	{TimerGoing: 0},
	{TimerLayout: 0},
	{IsFullscreen: 0},
	{Song: 0}
];

self.InstanceType = {
	MovingText: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Buttons: class extends self.ISpriteInstance {},
	ChangeCurser: class extends self.ITextInstance {},
	TimerDisplay: class extends self.ISpriteInstance {},
	InputText: class extends self.ITextInstance {},
	TimerDidgets1: class extends self.ITextInstance {},
	TimerDidgets2: class extends self.ITextInstance {},
	TimerDidgets3: class extends self.ITextInstance {},
	Colon: class extends self.ITextInstance {},
	TimerDidgets4: class extends self.ITextInstance {},
	Number1: class extends self.ITextInstance {},
	NumberAlignment: class extends self.ISpriteInstance {},
	Number2: class extends self.ITextInstance {},
	Number3: class extends self.ITextInstance {},
	Number4: class extends self.ITextInstance {},
	Number5: class extends self.ITextInstance {},
	Number6: class extends self.ITextInstance {},
	Number7: class extends self.ITextInstance {},
	Number8: class extends self.ITextInstance {},
	Number9: class extends self.ITextInstance {},
	Number10: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	Timer: class extends self.ITextInstance {},
	OptionSelect: class extends self.IButtonInstance {},
	OptionText1: class extends self.ITextInstance {},
	GotoMenu: class extends self.ISpriteInstance {},
	FakeCountdownToggle: class extends self.IButtonInstance {},
	KeyboardInput: class extends self.ITextInputInstance {},
	ActiveKeyboard: class extends self.ISpriteInstance {},
	ActivKeyboardLabel: class extends self.ITextInstance {},
	GotoMenu2: class extends self.ISpriteInstance {},
	OptionText2: class extends self.ITextInstance {},
	VolumeBar: class extends self.ISliderBarInstance {},
	FakeVolumeBar: class extends self.ISliderBarInstance {},
	Browser: class extends self.IInstance {},
	Fullscreen: class extends self.ISpriteInstance {},
	Exit: class extends self.ISpriteInstance {}
}